project:
  type: website
  output-dir: docs

website:
  title: "My test website"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Assignments"
        contents:
        - href: ae03-gerrymander.qmd
          text: "AE 03 - Gerrymandering"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  
      

format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true



